### PR TITLE
ENACT-131: Fixed Spotlight remains on ArcPicker after tap

### PR DESCRIPTION
**Pull request by stanca-pop-lgp**
Enact-DCO-1.0-Signed-off-by: Stanca Pop stanca.pop@lgepartner.com

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [x] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [x] Documentation was verified or is not changed
* [x] UI test was passed or is not needed
* [x] Screenshot test was verified or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Spotlight remains on ArcPicker after tap.

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
- Added a setTimeout to handle Spotlight on ArcPicker for touch devices.

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
ENACT-131

### CODE REVIEW

**Comment by stanca-pop-lgp** [comment]
Build fails because unit tests in develop branch are still using 'enzyme'. ("Cannot find module 'enzyme'")

**Review by daniel-stoian-lgp — COMMENTED** [review]
I don't think adding onPointerDown and onPointerUp brings any benefits to the implementation. They seem redundant.
Please test on branch feature/ENACT-131-DS. On Android it seems to fix the problem with less code https://github.com/enactjs/agate/compare/develop...feature/ENACT-131-DS

**Comment by stanca-pop-lgp** [comment]
> I don't think adding onPointerDown and onPointerUp brings any benefits to the implementation. They seem redundant. Please test on branch feature/ENACT-131-DS. On Android it seems to fix the problem with less code [develop...feature/ENACT-131-DS](https://github.com/enactjs/agate/compare/develop...feature/ENACT-131-DS) If this fixes the issue, please also update the changelog with description about the bugfix
> 
> Or are they designed for stylus? I'm not sure this should be a useCase for Agate

It only fixes the "click" part, meaning a quick tap (both finger and pen). If you simulate the hover effect you must keep your finger on the touchscreen for a little longer and release it afterwards (like you would take the mouse off your element). While you keep it on the screen it should be focused. I tried your branch and it doesn't have this behaviour. This is why I added those events so, the way I see it, it is not redundant.

**Review by vladut-clapou-lgp — APPROVED** [review]
LGTM

**Review by juwonjeong — APPROVED** [review]
LGTM

**Pull request merged**
