### PR TITLE
WRO-6381: Fix security vulnerabilities

### PR DESCRIPTION
**Pull request by hong6316**
### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [x] Documentation was verified or is not changed
* [x] UI test was passed or is not needed
* [x] Screenshot test was verified or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
For preventing malware issues, we need to update node modules that fix severity vulnerabilities.

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Update dependencies to the latest versions.

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)
Update the lockfile version to v2

### Links
[//]: # (Related issues, references)
WRO-6381

### Comments
Enact-DCO-1.0-Signed-off-by: Taeyoung Hong (taeyoung.hong@lge.com)

### CODE REVIEW

**Review by MikyungKim — COMMENTED** [review]
Would you please update the versions of the samples too?

**Comment by MikyungKim** [comment]
Please sign the CLA @hong6316.

**Review by MikyungKim — COMMENTED** [review]
Please update to the latest enact packages.

**Comment by hong6316** [comment]
> 

OK

**Comment by hong6316** [comment]
> Would you please update the versions of the samples too?

OK

**Comment by hong6316** [comment]
> Please sign the CLA @hong6316.

OK

**Comment by hong6316** [comment]
> Please update to the latest enact packages.

OK

**Review by MikyungKim — APPROVED** [review]
LGTM

**Pull request merged**
