### PR TITLE
PLAT-122734: Reverted incrementSlider button color for Gallium

### PR DESCRIPTION
**Pull request by daniel-stoian-lgp**
Enact-DCO-1.0-Signed-off-by: Daniel Stoian daniel.stoian@lgepartner.com

**Checklist**
 I have read and understand the contribution guide
 A CHANGELOG entry is included

**Issue Resolved / Feature Added**
Agate - Reverted incrementSlider button color for Gallium. It was altered when developing IncrementSlider for Silicon in  #286 and this issue was highlighted in the screenshot tests.

**Links**
PLAT-122734

### CODE REVIEW

**Review by adrian-cocoara-lgp — APPROVED** [review]
LGTM

**Review by ybsung — APPROVED** [review]
LGTM

I update CHANGELOG.md which is actually not related with this PR.

**Comment by jeonghee27** [comment]
I cannot understand the resolution and cause from 
>"Fixed incrementSlider button color for Gallium

it's too lack of information
Please leave more detail description

Actually we have official PR description format. 
Please refer https://github.com/enactjs/agate/pull/354 (it's just mine, not best example)
Even if you don't follow this form, anyway we need a more description to understand the issue and solution.

**Comment by jeonghee27** [comment]
In the case of revert or partial revert, we need to refer to the original PR number to be linked each PR.
I've found this is a partial reversal from https://github.com/enactjs/agate/pull/286. is it right? Please add this to the description.


Also, after reflecting the review, please write a comment again or assign ticket to the reviewer, so that we can precess review as soon as possible.

**Comment by daniel-stoian-lgp** [comment]
> In the case of revert or partial revert, we need to refer to the original PR number to be linked each PR.
> I've found this is a partial revert from #286. is it right? Please add this to the description.
> 
> Also, after reflecting the review, please write a comment again or assign ticket to the reviewer, so that we can precess review as soon as possible.

Thank you for the guidance. 
Yes, it's a partial revert of #286

**Pull request merged**
