### PR TITLE
PLAT-141624: Fixed PopupMenu closeButton label color

### PR DESCRIPTION
**Pull request by stanca-pop-lgp**
Enact-DCO-1.0-Signed-off-by: Stanca Pop stanca.pop@lgepartner.com

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [x] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [x] Documentation was verified or is not changed
* [x] UI test was passed or is not needed
* [x] Screenshot test was verified or is not needed
* [ ] This is an API breaking change

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
On Gallium and Silicon skin, for day mode, closeButton had a different color for label, so I changed it to match the other labeledIconButtons' labels in PopupMenu component.

### Links
[//]: # (Related issues, references)
PLAT-141624

### Comments

### CODE REVIEW

**Review by daniel-stoian-lgp — APPROVED** [review]
Frumos, elegant

**Review by seunghoh — CHANGES_REQUESTED** [review]
From the GUI https://app.zeplin.io/project/5fab9d1c39e44d926043ec54/screen/6033438526a126114f4685e3
text color is not white. This is only changing the cancel label color and are you going to follow this on the separate ticket? If yes, please let me know

**Comment by stanca-pop-lgp** [comment]
> From the GUI https://app.zeplin.io/project/5fab9d1c39e44d926043ec54/screen/6033438526a126114f4685e3
> text color is not white. This is only changing the cancel label color and are you going to follow this on the separate ticket? If yes, please let me know

@seunghoh You are correct, the LabeledIconButton has a different color for label. There was a forced style for the PopupMenu labels in the sampler, but I removed it, leaving it to inherit the colors from LabeledIconButton component. They are now the same color, as it was intended. Thank you!

**Comment by seunghoh** [comment]
GUI shows
image
but I see the sample from Silicon dark mode
image

Again, please let me know if I misunderstand your intention. if you just focus on making the label color of cancel button same as other and will follow up other GUI (like focused style etc.). It also fine

**Review by seunghoh — APPROVED** [review]

**Review by seunghoh — APPROVED** [review]
LGTM

**Pull request merged**
