### PR TITLE
FORTECH-103: Create sampler for TabGroup, Switch, VirtualGridList

### PR DESCRIPTION
**Pull request by adrian-cocoara-lgp**
Created sampler for TabGroup, Switch, VirtualGridList

Enact-DCO-1.0-Signed-off-by: Adrian Cocoara adrian.cocoara@lgepartner.com

### CODE REVIEW

**Review by daniel-stoian-lgp — APPROVED** [review]
LGTM

**Comment by ybsung** [comment]
Hello @adrian-cocoara-lgp 

I realized that we needed to update Checkbox and Switch to support A11y features as you did. I think that it is not good time to change the code of Checkbox and Switch. So @seunghoh and I decided to remove the Checkbox and the Switch samplers because of not support A11y features.

So could you revert the code for Switch component and Switch sampler. Sorry for changing the requirement.

Other samplers looks good to me.

**Comment by adrian-cocoara-lgp** [comment]
> Hello @adrian-cocoara-lgp
> 
> I realized that we needed to update Checkbox and Switch to support A11y features as you did. I think that it is not good time to change the code of Checkbox and Switch. So @seunghoh and I decided to remove the Checkbox and the Switch samplers because of not support A11y features.
> 
> So could you revert the code for Switch component and Switch sampler. Sorry for changing the requirement.
> 
> Other samplers looks good to me.

Sure, no worries

**Review by ybsung — APPROVED** [review]
LGTM

**Pull request merged**
