### PR TITLE
WRN-20804: MediaPlayer layout improvements

### PR DESCRIPTION
**Pull request by adrian-cocoara-lgp**
Enact-DCO-1.0-Signed-off-by: Adrian Cocoara adrian.cocoara@lgepartner.com

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [x] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [x] Documentation was verified or is not changed
* [x] UI test was passed or is not needed
* [x] Screenshot test was verified or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Added some layout improvements to MediaPlayer on Carbon, Cobalt, Copper, Titanium skins

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
WRO-20804

### CODE REVIEW

**Review by daniel-stoian-lgp — APPROVED** [review]

**Comment by stanca-pop-lgp** [comment]
Without changing the slider style (which is too big on some skins), I would suggest adjusting the styling a bit more to resemble Silicon and Gallium skins. 
What I mean is the distance between the the times and the media player edges and between the times and the slider.
In Silicon it looks like this:
image
In other skins: 
image
or
image
So I suggest adding a bit more distance like this:
image
This is what I changed:
image
Also please group margin-left and margin-right in one value.

**Comment by stanca-pop-lgp** [comment]
You still have to fix it for Electro skin:
image
And a tiny bit (vertically) for Carbon. When knob is pressed it's too close to times:
image
Thanks!

**Comment by stanca-pop-lgp** [comment]
Also, please adjust the border radius for the play button for Carbon, Cobalt, Copper, Electro, Titanium.

**Review by stanca-pop-lgp — APPROVED** [review]
LGTM

**Pull request merged**
