### PR TITLE
FORTECH-116: RadioItem - Hover style not the same as Zeplin

### PR DESCRIPTION
**Pull request by adrian-cocoara-lgp**
Hover over RadioItem bug fixed for Silicon skin to match Zepplin design
Changed default children text in sample from 'Sound' -> 'Hello RadioItem' so it would be more appropriate

Enact-DCO-1.0-Signed-off-by: Adrian Cocoara adrian.cocoara@lgepartner.com

### CODE REVIEW

**Review by daniel-stoian-lgp — APPROVED** [review]
LGTM

**Review by ybsung — APPROVED** [review]
LGTM

**Comment by jeonghee27** [comment]
Could you modify the other skins with the same rule?

**Comment by daniel-stoian-lgp** [comment]
> Could you modify the other skins with the same rule?

@jeonghee27, are we allowed to modify the other skins? Wouldn't it break some requirements for those skins?

**Comment by jeonghee27** [comment]
> > Could you modify the other skins with the same rule?
> 
> @jeonghee27, are we allowed to modify the other skins? Wouldn't it break some requirements for those skins?

Of course your team can modify all other skins.
There is no GUI other than Gallium.
This obvious problem would be fine to apply to all.

**Pull request merged**
