### PR TITLE
PLAT-141497: ColorPicker - layout bug

### PR DESCRIPTION
**Pull request by adrian-cocoara-lgp**
### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [x] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [x] Documentation was verified or is not changed
* [x] UI test was passed or is not needed
* [x] Screenshot test was verified or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
`ColorPicker` has a layout bug for Carbon, Electro, Gallium, Silicon skins (color options has wrong position)
On Silicon night the background color of `ColorPicker` is not visible 

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Added a padding for layout bug
Changed background-color of ColorPicker for Silicon skin

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
PLAT-141497

### Comments

Enact-DCO-1.0-Signed-off-by: Adrian Cocoara adrian.cocoara@lgepartner.com

### CODE REVIEW

**Review by daniel-stoian-lgp — APPROVED** [review]
LGTM

**Review by stanca-pop-lgp — APPROVED** [review]
LGTM

**Review by seunghoh — CHANGES_REQUESTED** [review]
Well... OK for adding padding but looks akward on colorpicker background color - bg color stays gray on day & night but text color changes from white to black.
Gallium as well (It's not related this PR but), colorpicker bg color looks award. 
Have you ever tried with popup background color? Using popup-bg-color makes sense to me since color picker looks popup family.

**Review by seunghoh — APPROVED** [review]
LGTM Thanks!

**Pull request merged**
