### PR TITLE
PLAT-139055: Fixed popup title when centered

### PR DESCRIPTION
**Pull request by daniel-stoian-lgp**
### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [x] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [x] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [x] Documentation was verified or is not changed
* [x] UI test was passed or is not needed
* [x] Screenshot test was verified or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Title is not fully centered inside the popup, but a little bit to the left.

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Updated styling for all skins to center the title when `centered`.
For silicon skin, the title and content container fixed width was removed because it affected the title position on `centered`. Instead a fixed width was added for the Popup container, based on the UI spec

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
PLAT-139055

### Comments

Enact-DCO-1.0-Signed-off-by: Daniel Stoian daniel.stoian@lgepartner.com

### CODE REVIEW

**Comment by stanca-pop-lgp** [comment]
Please check the popup body layout.

image

**Comment by stanca-pop-lgp** [comment]
Also, on Titanium, when 'centered' is false, title has an unnecessary padding-left.

image

**Comment by stanca-pop-lgp** [comment]
On Carbon, the title goes over the close button, even when marquee is applied with #577.

image

**Comment by stanca-pop-lgp** [comment]
On Silicon as well.

image

**Comment by daniel-stoian-lgp** [comment]
> Please check the popup body layout on Silicon skin when 'centered' is true.
> 
> image

Please give more details about the used knobs. On my computer, the layout looks OK

image

**Comment by daniel-stoian-lgp** [comment]
> On Silicon as well.
> 
> image

Marquee works for me, if I apply the changes from #577 

image

**Comment by stanca-pop-lgp** [comment]
Could you add a bit more padding-left to the title so that it doesn't stick to the button (only when aligned left)? Also please fix the button's icon color.  (for Cobalt and Copper skins)

image

**Comment by adrian-cocoara-lgp** [comment]
> Could you add a bit more padding-left to the title so that it doesn't stick to the button (only when aligned left)? Also please fix the button's icon color. (for Cobalt and Copper skins)
> 
> image

I would also add here... maybe the position of button for this skin to be moved to the right to match other skins

**Comment by stanca-pop-lgp** [comment]
image

Maybe just preserve the 12px margin like on RTL:
image

**Comment by stanca-pop-lgp** [comment]
On Titanium, when not centered, remove the padding on the opposite side of the close button. Also add a little bit more padding to the title like for Cobalt and Copper skins.

image

**Comment by stanca-pop-lgp** [comment]
On Silicon, when not centered, please align the title with the body content like in the design. (smaller padding when centered=false)

image

**Comment by daniel-stoian-lgp** [comment]
> image
> 
> Maybe just preserve the 12px margin like on RTL:
> image

I think what you showed is just a optical illusion caused by the letter-spacing of 12px

**Comment by stanca-pop-lgp** [comment]
> > image
> > Maybe just preserve the 12px margin like on RTL:
> > image
> 
> I think what you showed is just a optical illusion caused by the letter-spacing of 12px

Yes, you are correct. I still suggest that you separate a bit the title from the button, but it's your call. ;)

**Review by stanca-pop-lgp — APPROVED** [review]
LGTM

**Pull request closed without merging**
