### PR TITLE
FORTECH-112: Picker components - disable state is not reflected on the styles

### PR DESCRIPTION
**Pull request by stanca-pop-lgp**
Feature Added
Fixed bug on Picker component.

Comments
Fixed bugs and adjusted styling of Picker component in Agate. 
- added disabled styling for active bar;
- removed focus state on increment and decrement values when disabled is selected;
- aligned general styles with Zeplin design.

Enact-DCO-1.0-Signed-off-by: Stanca Pop stanca.pop@lgepartner.com

### CODE REVIEW

**Review by daniel-stoian-lgp — APPROVED** [review]
LGTM

**Review by ybsung — APPROVED** [review]
LGTM
But, I have one concern. With the PR, the disabled Picker couldn't get focus via 5-way keys. It would be fine with the current UX and touch devices. But we need to make a decision whether the disabled component could get focus like Sandstone or not in Agate.

**Comment by ybsung** [comment]
> 1 pending reviewer
> adrian-cocoara-lgp was requested for review

Is there anything that @adrian-cocoara-lgp requested to fix?

**Comment by ybsung** [comment]
> Is there anything that @adrian-cocoara-lgp requested to fix?
Now it resolved.

**Pull request closed without merging**
