### PR TITLE
PLAT-119496: Remove unnecessary margin-top style from stories of sampler

### PR DESCRIPTION
**Pull request by jeonghee27**
Enact-DCO-1.0-Signed-off-by: Jeongran Jang <jeongran.jang@lge.com>

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Need a space between a header and a body content in a Panel

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
The issue will be resolved on PLAT-123186, because the default size is "medium" , then the "mediumSpacing" style will be applied.
In this PR, I just removed unnecessary margin-top style on some Samplers

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
PLAT-119496

### Comments

### CODE REVIEW

**Comment by ybsung** [comment]
Please fix the lint errors.
```
/agate/samples/sampler/stories/default/ArcPicker.js
  4:8  warning  'ri' is defined but never used  no-unused-vars

/agate/samples/sampler/stories/default/ArcSlider.js
  4:8  warning  'ri' is defined but never used  no-unused-vars

/agate/samples/sampler/stories/default/TemperatureControl.js
  4:8  warning  'ri' is defined but never used  no-unused-vars

/agate/samples/sampler/stories/default/WindDirectionControl.js
   2:8   warning  'ri' is defined but never used              no-unused-vars
  16:57  warning  A space is required before closing bracket  react/jsx-tag-spacing
```

**Comment by ybsung** [comment]
Please check if the following margins and paddings are needed.

```
// ContextualPopupDecorator sampler
<div style={{textAlign: 'center', marginTop: ri.scaleToRem(99)}}>
<div style={{textAlign: 'center', marginTop: ri.scaleToRem(99)}}>

// Image sampler
				style={{
					border: '#ffa500 dashed 1px',
					marginTop: ri.scaleToRem(50)
				}}

// ImageItem sampler
<div style={{width: ri.scaleToRem(400), height: ri.scaleToRem(300)}}>


// samples/sampler/stories/default/ImageItemKitchenSink.js
<div style={{width: ri.scaleToRem(400), height: ri.scaleToRem(300)}}>

// Picker sampler
<div style={{padding: '0 20%'}}>

// Spinner sampler
			<div
				style={{
					outline: 'teal dashed 1px',
					position: 'relative',
					padding: ri.unit(90, 'rem'),
					backgroundColor: 'rgba(0, 187, 187, 0.5)'
				}}

// TabbedPanels
<div style={{paddingBottom: '56.25%'}}>
```

**Review by ybsung — APPROVED** [review]
LGTM

**Comment by MikyungKim** [comment]
Great! How do you feel about adding some space to Panels and Panel sample? It looks too tight.
image
image

**Comment by jeonghee27** [comment]
> Great! How do you feel about adding some space to Panels and Panel sample? It looks too tight.
> image
> image

Because I couldn't find the margin value defined in Zeplin, I added the top padding using the value used in the pannel. 
(In other skins execpt silicon and galium, header padding is used as the value of @agate-panels-panel-padding.) 
@agate-panels-panel-header-padding: @agate-panels-panel-padding;

**Comment by jeonghee27** [comment]
> Great! How do you feel about adding some space to Panels and Panel sample? It looks too tight.
> image
> image

I added `marginBottom: ri.scaleToRem(18)` on each sampler.

**Comment by MikyungKim** [comment]
The other skins have paddings in Panel's body so we've decided not to fix Panels and Panel sample.

**Review by MikyungKim — APPROVED** [review]
:shipit:

**Pull request merged**
