### PR TITLE
FORTECH-108: Fix to compile JS documentation properly

### PR DESCRIPTION
**Pull request by ybsung**
Fix to compile JS documentation properly

Enact-DCO-1.0-Signed-off-by: YB Sung (yb.sung@lge.com)

### CODE REVIEW

**Comment by ybsung** [comment]
@adrian-cocoara-lgp fixed the issue. I just created the PR based on his patch.

**Comment by ybsung** [comment]
Actually, we have to apply `left: -50% ` in my commit -https://github.com/enactjs/agate/pull/346/commits/766de8de3f4ce7363aeaf018e22ca64410e3bad7. But due to the `overflow: hidden` in the parent DOM element, the divider could be clipped. We can't remove the overflow css style. So I just simply apply `left: 0` here.

**Review by jeonghee27 — APPROVED** [review]
LGTM
I checked the result on Jenkins enact-docs/502/

**Comment by MikyungKim** [comment]
:shipit:

**Pull request merged**
